const express = require('express')
const dotenv = require('dotenv')
const cors = require('cors')
const connectDB = require('./config/db')
const bookRoutes = require('./routes/bookRoutes')
const reviewRoutes = require('./routes/reviewRoutes')
const userRoutes = require('./routes/userRoutes')

dotenv.config()
connectDB()
const app = express()
app.use(cors())
app.use(express.json())
app.use('/api/books', bookRoutes)
app.use('/api/reviews', reviewRoutes)
app.use('/api/users', userRoutes)
app.listen(process.env.PORT, () => console.log('Server running'))
